#!/bin/bash
# 
# author: brando
# date: 5/2/24
#

## CONSTANTS

SCRIPT_NAME=$(basename $0);
SCRIPT_PATH=$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P );
V_ARGS=( "$@" );
C_ARGS=${#V_ARGS[@]};

## GLOBALS

source $SCRIPT_PATH/install_utils.sh

# 
# help()
#
# returns none
function help() {
	printf "usage: $SCRIPT_NAME\n";
	printf "\n";
	printf "Creates a goto folder in your home directory and stores all components in it\n";
	printf "\n";
	printf "Copyright © 2024 Brando. All rights reserved.\n";
}

#
# install()
#
# returns error code
function install() {
	#local targetpath=~/$GOTO_UTILS_DIR_NAME;
	local targetpath=$GOTO_UTILS_DATA_DIR;

	# make the goto utils dir
	if [ ! -d $targetpath ]; then
		mkdir $targetpath;
		if [ $? -ne 0 ]; then
			printf "error: could not create $targetpath\n";
			return 1;
		fi
	fi

	# copy components
	for comp in "${GOTO_COMPONENTS[@]}"
	do
		cp -afv $SCRIPT_PATH/$comp $targetpath;
		if [ $? -ne 0 ]; then
			printf "error: cp returned $?\n";
			return $?;
		elif [ ! -f $targetpath/$comp ]; then
			printf "error: could not copy over component: $comp\n";
			return 2;
		fi
	done

	# create the completions file for zsh
	if [ -n $ZSH_VERSION ]; then
		goto-completion-zsh-reload;
	fi

	return 0;
}

#
# main()
#
# exits with an error code
function main() {
	arguments_read;
	if [ $? -ne 0 ]; then
		exit $?;
	fi

	if [ $gShowHelp == true ]; then
		help;
	else
		install;
		if [ $? -ne 0 ]; then
			exit $?;
		else
			printf "Installation complete\n";
			printf "Please add the following to your shell profile:\n";
			printf "\`source ~/$GOTO_UTILS_DATA_DIR_NAME/$GOTO_ENV_FILE_NAME;\`\n";
		fi
	fi

	exit 0;
}

main;

